# Generated by Django 5.0.6 on 2026-06-19 22:46

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_referral_code',
            field=models.CharField(blank=True, help_text='Referral code used during signup', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refferal_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdesqp1234567890', blank=True, help_text='Unique referral code for this user', length=12, max_length=30, null=True, prefix='ref_'),
        ),
    ]
