# Generated by Django 5.0.6 on 2026-06-19 22:46

from django.db import migrations
import shortuuid


def populate_referral_codes(apps, schema_editor):
    """Populate refferal_code for all users with NULL or empty values"""
    User = apps.get_model('account', 'User')
    su = shortuuid.ShortUUID(alphabet='FR1234567890')
    
    # Get all users with NULL or empty refferal_code
    for user in User.objects.filter(refferal_code__in=['', None]):
        # Generate a unique code with prefix
        code = 'AB' + su.random(8)
        # Ensure it's unique
        while User.objects.filter(refferal_code=code).exists():
            code = 'AB' + su.random(8)
        user.refferal_code = code
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_signup_referral_code_alter_user_refferal_code'),
    ]

    operations = [
        migrations.RunPython(populate_referral_codes),
    ]
