# Generated by Django 5.0.6 on 2026-06-19 22:54

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_populate_refferal_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refferal_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='FR1234567890', help_text='Unique referral code for this user', length=8, max_length=30, prefix='AB', unique=True),
        ),
    ]
