# Generated by Django 5.0.6 on 2026-06-19 23:00

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_refferal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refferal_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', help_text='Unique referral code for this user', length=6, max_length=30, prefix='AB', unique=True),
        ),
    ]
