# Generated by Django 5.2.7 on 2025-10-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='ipn_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pay_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pay_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pay_currency',
            field=models.CharField(default='btc', max_length=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_status',
            field=models.CharField(default='waiting', max_length=20),
        ),
    ]
