# Generated by Django 5.2.7 on 2025-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deposit_ipn_processed_deposit_pay_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='network',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='pay_currency',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('sol', 'Solana (SOL)'), ('usdtbep20', 'USDT BEP20'), ('usdttrc20', 'USDT TRC20'), ('eth', 'Ethereum (ETH)')], default='btc', max_length=10),
        ),
    ]
