# Generated by Django 5.2.7 on 2025-10-29 09:31

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deposit_network_alter_deposit_pay_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='actual_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='crypto_currency',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('eth', 'Ethereum (ETH)'), ('sol', 'Solana (SOL)'), ('usdt_bep20', 'USDT BEP20')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially Paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdesqp1234567890', length=10, max_length=10, prefix='wit_', primary_key=True, serialize=False, unique=True),
        ),
    ]
