# Generated by Django 5.2.7 on 2025-10-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deposit_actual_amount_withdrawal_crypto_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='last_profit_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
