# Generated by Django 5.2.7 on 2025-11-06 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_investment_last_profit_update_investment_profit_made'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='network',
        ),
        migrations.AddField(
            model_name='deposit',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the deposit was completed', null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the withdrawal was completed', null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='crypto_amount',
            field=models.DecimalField(decimal_places=8, help_text='Amount in cryptocurrency', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='actual_amount',
            field=models.DecimalField(decimal_places=8, help_text='Actual amount received in cryptocurrency', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Deposit amount in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='ipn_processed',
            field=models.BooleanField(default=False, help_text='Whether the IPN webhook has been processed'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='pay_address',
            field=models.CharField(blank=True, help_text='Cryptocurrency address for payment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Amount in cryptocurrency to pay', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='pay_currency',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('sol', 'Solana (SOL)'), ('usdtbep20', 'USDT BEP20'), ('usdttrc20', 'USDT TRC20'), ('eth', 'Ethereum (ETH)')], help_text='Selected cryptocurrency for payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_id',
            field=models.CharField(blank=True, help_text='NOWPayments payment ID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'Waiting for Payment'), ('confirming', 'Confirming on Blockchain'), ('confirmed', 'Confirmed on Blockchain'), ('sending', 'Sending to Merchant'), ('partially_paid', 'Partially Paid'), ('finished', 'Payment Complete'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded'), ('expired', 'Payment Expired'), ('cancelled', 'Payment Cancelled')], default='waiting', help_text='Current payment status from NOWPayments', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Withdrawal amount in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='crypto_currency',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('sol', 'Solana (SOL)'), ('usdtbep20', 'USDT BEP20'), ('usdttrc20', 'USDT TRC20'), ('eth', 'Ethereum (ETH)')], help_text='Cryptocurrency for withdrawal', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Destination wallet address', max_length=100, null=True),
        ),
    ]
