# Generated by Django 5.2.7 on 2025-11-11 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_deposit_network_deposit_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposits'},
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['payment_id'], name='core_deposi_payment_f745af_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user', 'status'], name='core_deposi_user_id_82871c_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['created_at'], name='core_deposi_created_d65564_idx'),
        ),
    ]
