# Generated by Django 5.2.7 on 2025-11-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_deposit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='pay_currency',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('sol', 'Solana (SOL)'), ('usdterc20', 'USDT ERC20'), ('usdttrc20', 'USDT TRC20'), ('eth', 'Ethereum (ETH)')], help_text='Selected cryptocurrency for payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='crypto_currency',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('sol', 'Solana (SOL)'), ('usdterc20', 'USDT ERC20'), ('usdttrc20', 'USDT TRC20'), ('eth', 'Ethereum (ETH)')], help_text='Cryptocurrency for withdrawal', max_length=20),
        ),
    ]
