# Generated by Django 5.2.7 on 2025-11-19 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_deposit_pay_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='actual_amount',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
