# Generated by Django 5.2.7 on 2025-11-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_deposit_actual_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'Waiting for Payment'), ('partially_paid', 'Partially Paid'), ('finished', 'Payment Complete'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded'), ('expired', 'Payment Expired'), ('cancelled', 'Payment Cancelled')], default='waiting', help_text='Current payment status from NOWPayments', max_length=20),
        ),
    ]
