# Generated by Django 5.2.7 on 2025-11-21 15:47

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_deposit_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Withdrawal', 'verbose_name_plural': 'Withdrawals'},
        ),
        migrations.AlterField(
            model_name='investment',
            name='plan_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdesqp1234567890', length=10, max_length=20, prefix='PPD', unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Amount in cryptocurrency', max_digits=20, null=True),
        ),
    ]
