# Generated by Django 5.2.7 on 2025-11-21 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_withdrawal_options_alter_investment_plan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
