# Generated by Django 5.2.7 on 2025-11-27 11:11

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_investment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdesqp1234567890', length=12, max_length=45, prefix='dep_', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='pay_currency',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('sol', 'Solana (SOL)'), ('usdterc20', 'USDT ERC20'), ('usdttrc20', 'USDT TRC20'), ('usdtbep20', 'USDT BEP20'), ('eth', 'Ethereum (ETH)')], help_text='Selected cryptocurrency for payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='crypto_currency',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('sol', 'Solana (SOL)'), ('usdterc20', 'USDT ERC20'), ('usdttrc20', 'USDT TRC20'), ('usdtbep20', 'USDT BEP20'), ('eth', 'Ethereum (ETH)')], help_text='Cryptocurrency for withdrawal', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdesqp1234567890', length=10, max_length=32, prefix='wit_', primary_key=True, serialize=False, unique=True),
        ),
    ]
