# Generated by Django 5.2.7 on 2025-11-27 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_deposit_deposit_id_alter_deposit_pay_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'Bitcoin'", max_length=100)),
                ('symbol', models.CharField(blank=True, help_text='Symbol like BTC', max_length=10, null=True)),
                ('deposit_address', models.CharField(blank=True, help_text='Default deposit address for this crypto', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cryptocurrency',
                'verbose_name_plural': 'Cryptocurrencies',
            },
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='deposit',
            name='core_deposi_payment_f745af_idx',
        ),
        migrations.RemoveIndex(
            model_name='deposit',
            name='core_deposi_user_id_82871c_idx',
        ),
        migrations.RemoveIndex(
            model_name='deposit',
            name='core_deposi_created_d65564_idx',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='ipn_processed',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='pay_address',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='pay_currency',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='crypto_amount',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='tx_hash',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deposit',
            name='crypto',
            field=models.ForeignKey(blank=True, help_text='Selected cryptocurrency for this deposit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='crypto_currency',
            field=models.ForeignKey(help_text='Cryptocurrency for withdrawal', on_delete=django.db.models.deletion.CASCADE, to='core.cryptocurrency'),
        ),
    ]
