# Generated by Django 5.2.7 on 2025-11-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cryptocurrency_alter_deposit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(blank=True, help_text='Symbol like BTC', max_length=30, null=True),
        ),
    ]
